export enum DomainErrorCode {
  JOB_TITLE_REQUIRED = 'JOB_TITLE_REQUIRED',
  JOB_TITLE_TOO_LONG = 'JOB_TITLE_TOO_LONG',
  JOB_NO_TECHNOLOGIES = 'JOB_NO_TECHNOLOGIES',
  JOB_FUTURE_DATE = 'JOB_FUTURE_DATE',
  SALARY_INVALID_RANGE = 'SALARY_INVALID_RANGE',
  SALARY_NEGATIVE = 'SALARY_NEGATIVE',
  SALARY_UNREALISTIC = 'SALARY_UNREALISTIC',
  TECHNOLOGY_NAME_REQUIRED = 'TECHNOLOGY_NAME_REQUIRED',
  TECHNOLOGY_INVALID_CATEGORY = 'TECHNOLOGY_INVALID_CATEGORY',
  REGION_CODE_INVALID = 'REGION_CODE_INVALID',
  JOB_EXPIRED = 'JOB_EXPIRED',
  JOB_TECH_NAME_TOO_LONG = 'JOB_TECH_NAME_TOO_LONG',
  JOB_DESCRIPTION_TOO_LONG = 'JOB_DESCRIPTION_TOO_LONG',
}

export class DomainError extends Error {
  constructor(
    public code: DomainErrorCode,
    public metadata?: Record<string, any>
  ) {
    super(code);
    this.name = 'DomainError';
  }
}
